version: "3.9"

services:
  app:
    build: .
    container_name: todo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mongo_data:
